### ISSUE TITLE
이 부분은 switch로 바꿔봅시다. 그리고 switch가 더 좋은 이유도 생각해봅시다.

### ISSUE THREAD

**Issue by f-lab-Digitz** [gugbab2/Cpp-Exercises#1]
https://github.com/gugbab2/Cpp-Exercises/blob/f6fed2984150b7116aff043ff00d6482610625bf/DAY10/exam2.cpp#L18

**Comment by gugbab2** [comment]
아래와 같이 if 에 비해 switch 가 다른 점을 생각할 수 있을 것 같습니다. 
(변경한 코드는 다시 커밋해두었습니다.)

[switch 문의 장점]
 1. 가독성이 높다. 
 2. 컴파일러가 상수 조건에 해당하는 코드블럭으로 Jump 해 불필요한 영역을 컴파일 하지 않는다.(컴파일 시간이 줄어든다) 

[switch 문의 단점]
 1. 복잡한 조건을 사용하지 못한다.(상수만 사용 가능하다.)
 -> C++11 이후부터는 문자, 열거형
 -> C++17 이후부터는 문자열까지 사용 가능하다.
