### ISSUE TITLE
이 부분은 Type Mismatch Warning이 날 수 있습니다. 고쳐봅시다.

### ISSUE THREAD

**Issue by f-lab-Digitz** [gugbab2/Cpp-Exercises#2]
https://github.com/gugbab2/Cpp-Exercises/blob/f6fed2984150b7116aff043ff00d6482610625bf/DAY10/exam4.cpp#L15

**Comment by gugbab2** [comment]
vector 의 size() 의 함수는 size_t 타입의 변수를 리턴하게 되는데 현재 i는 int 타입이기 때문에, Type Mismatch Warning 이 발생할 수 있습니다.
