### ISSUE TITLE
이부분은 algorithm 을 써서 풀어봅시다.

### ISSUE THREAD

**Issue by f-lab-Digitz** [gugbab2/Cpp-Exercises#3]
https://en.cppreference.com/w/cpp/algorithm/find 이걸 참조해보세요.

https://github.com/gugbab2/Cpp-Exercises/blob/f6fed2984150b7116aff043ff00d6482610625bf/DAY10/exam4.cpp#L24

**Comment by gugbab2** [comment]
algorithm find() 함수를 사용했습니다. 

find 함수 내부 구현이 o(n) 으로 보여지는데, 맞을까요?
저번 멘토링 시간에 o(n) 이라고 말씀하셨던 부분이 기억나는데, 제가 잘못들은 것인지 확인 차 말씀드립니다.
