### ISSUE TITLE
단순한 copy를 이렇게 길게 적으면 가독성이 떨어집니다. Algorithm을 이용해보세요.

### ISSUE THREAD

**Issue by f-lab-Digitz** [gugbab2/Cpp-Exercises#5]
https://en.cppreference.com/w/cpp/algorithm/copy
를 참고해보세요.
https://github.com/gugbab2/Cpp-Exercises/blob/f6fed2984150b7116aff043ff00d6482610625bf/DAY10/exam5.cpp#L19

**Comment by gugbab2** [comment]
assign 함수를 통해서 answer 를 재할당하는 방식으로 변경하였습니다.
