### ISSUE TITLE
이건 왜 Temp를 둬서 다시 카피를 했나요?

### ISSUE THREAD

**Issue by f-lab-Digitz** [gugbab2/Cpp-Exercises#6]
https://github.com/gugbab2/Cpp-Exercises/blob/f6fed2984150b7116aff043ff00d6482610625bf/DAY10/exam5.cpp#L14

**Comment by gugbab2** [comment]
temp  를 만들 필요 없이, arr 을 사용했으면 되었을 부분인 것 같습니다.
