### ISSUE TITLE
알고리즘을 쓰는 연습을 해봅시다.

### ISSUE THREAD

**Issue by f-lab-Digitz** [gugbab2/Cpp-Exercises#8]
https://en.cppreference.com/w/cpp/algorithm/transform
이 구문을 참조해보세요.

https://github.com/gugbab2/Cpp-Exercises/blob/f6fed2984150b7116aff043ff00d6482610625bf/DAY9/exam3.cpp#L16

**Comment by gugbab2** [comment]
transform 함수를 사용해 개선했습니다.
